### ISSUE TITLE
how can i get all domains

### ISSUE THREAD

**Issue by maxmonkey950** [eXamadeus/godaddypy#13]
how can i get all domains, i used client.get_domains() to get all doamins,  but i get a little only. i find the limit args in official docmetion, but i do not know how to use... help me. think you

**Comment by ezrubaal** [comment]
same issue, following

**Comment by maxmonkey950** [comment]
> same issue, following
@ezrubaal
hey, i have solved it, use the marker to mark the domains order, you can refer https://github.com/maxmonkey950/godaddypy/blob/master/checkdomain.py

**Comment by eXamadeus** [comment]
I added this functionality in https://github.com/eXamadeus/godaddypy/releases/tag/2.3.3

You can now use the `Client.get_domains` method to directly interface with the API using its query parameters.  See the [GoDaddy documentation](https://developer.godaddy.com/doc/endpoint/domains#/v1/list).

You can use it like so:

```python
>>> client.get_domains(limit=4)
['abc.com', '123.org', 'banana.com', 'apple.com']
>>> client.get_domains(limit=2, marker='123.org')
['banana.com', 'apple.com']
```
