### ISSUE TITLE
Bug in `update_ip` for Python 3

### ISSUE THREAD

**Issue by asonnino** [eXamadeus/godaddypy#15]
In function `update_ip` of `client.py`,  the following check does not work for python 3:
```
if (
    subdomains is None or
    (isinstance(subdomains, (unicode, str)) and r_name == subdomains) or
     r_name in subdomains
):
```

This seems a bug as the rest of the function is careful in specifying behaviours for both python 2 and python 3. That is easy to fix, the check could simply become  as follows for python 3:
```
if (
    subdomains is None or
    (isinstance(subdomains, str) and r_name == subdomains) or
     r_name in subdomains
):
```

**Comment by eXamadeus** [comment]
This has been fixed in https://github.com/eXamadeus/godaddypy/releases/tag/2.4.1
