### ISSUE TITLE
[BUG] Missing dependencies

### ISSUE THREAD

**Issue by chrisspen** [eXamadeus/godaddypy#53]
**Describe the bug**
Your requirements are not correctly documented, causing them to not be installed, resulting in a broken package. The install_requires parameter in your setup.py needs to include everything in your requirements.txt.

**To Reproduce**

    python3.11 -m venv .env
    . .env/bin/activate
    pip install GoDaddyPy==2.5.1
    python -c "from godaddypy import Client, Account"

**Expected behavior**
Package should be importable after installation. Instead, package throws the error: ModuleNotFoundError: No module named 'configloader'

**Comment by chrisspen** [comment]
I'll create a PR to fix this.

**Comment by eXamadeus** [comment]
Solved in #54, #56

**Comment by jasonmcaffee** [comment]
I am encountering this issue with the latest 2.5.1
