### ISSUE TITLE
2.5.0 and 2.5. error ：TypeError: unsupported operand type(s) for |: 'type' and 'NoneType' 

### ISSUE THREAD

**Issue by neoshui** [eXamadeus/godaddypy#74]
![image](https://github.com/eXamadeus/godaddypy/assets/22654658/d2701c4a-9df3-4bae-93ea-66748e6b93c7)
![image](https://github.com/eXamadeus/godaddypy/assets/22654658/07cb78d5-60f1-4194-acff-68af00ae09f0)

**Comment by denialmx** [comment]
What version of python are you using?
I believe you need python 3.10, this seems to fail on 3.9

**Comment by neoshui** [comment]
> What version of python are you using? I believe you need python 3.10, this seems to fail on 3.9

yes，I found that
