### ISSUE TITLE
Add tox test suite to godaddypy

### ISSUE THREAD

**Issue by eXamadeus** [eXamadeus/godaddypy#8]
Currently, the unit tests only get run against multiple versions of python through travis CI.  It would be nice to have a local configuration (something like tox) that would run tests against a battery of different python versions so that developers can see if a test will fail in a certain version before having to push the commit and have CI catch the error.

**Comment by digitronik** [comment]
@eXamadeus I think at least we have to add some sanity checks like
1. flake8
2. black
3. run unit tests

**Note:** locally as well this check should be on Travis to maintain code quality

**Comment by eXamadeus** [comment]
Yeah it's been a while since I've touched this library. I think there is a LOT that can be done in regards to testing.

Thanks for the suggestions.

**Comment by digitronik** [comment]
@eXamadeus awesome!
I will add it at the weekend.

**Comment by eXamadeus** [comment]
This has been superseded by work in the latest release: https://github.com/eXamadeus/godaddypy/releases/tag/2.4.1

Unit tests are run through GitHub actions against multiple python versions. Black and flake8 are also checked as well.

Also we use PyTest now instead of nose.
